### ISSUE TITLE
save the file

### ISSUE THREAD

**Issue by Arthur-Milchior** [hernanat/dcolor#2]
Hi,

Thanks for your script. That's exactly what I was looking for. Except for one point. I can't figure out how to save the script; apart from doing it by hand. Could you please explain to me how to save the image ?

Regards,
Arthur

**Comment by hernanat** [comment]
Hey @Arthur-Milchior --

With the standard instructions, you could just run the program and hit the saving button as seen here:

![Screen Shot 2019-04-04 at 12 49 27 AM](https://user-images.githubusercontent.com/20129498/55532485-b0443a80-5673-11e9-89bf-e2d5ce447b10.png)

however, if you want to save it directly, you can add this line in the `plot` method right before `plt.show()`:

```python
plt.savefig('foo.png', bbox_inches='tight')
```

so that the whole method is:

```python
    def plot(self, f, xdim=10, ydim=8, plt_dpi=100):
        """Plot a complex-valued function
            Arguments:
            f -- a (preferably) lambda-function defining a complex-valued function
            Keyword Arguments:
            xdim -- x dimensions
            ydim -- y dimensions
            plt_dpi -- density of pixels per inch
        """
        zz=f(self.z(self.xx,self.yy))
        H,S,V = self.makeColorModel(zz)
        rgb = hsv_to_rgb(np.dstack((H,S,V)))

        fig = plt.figure(figsize=(xdim, ydim), dpi=plt_dpi)
        plt.imshow(rgb)
        plt.gca().invert_yaxis() #make CCW orientation positive
        plt.gca().get_xaxis().set_visible(False)
        plt.gca().get_yaxis().set_visible(False)
        plt.savefig('foo.png', bbox_inches='tight')
        plt.show()

```

that or you can remove `plt.show()` all together and replace it with that line.

I plan on making some changes to this script to make it more useable / all-purpose, I just don't have the time at the moment. Feel free to open up a PR with any changes you think might be helpful.

Best,

AFH

**Comment by Arthur-Milchior** [comment]
Already done, thank you
